export const students = [
  {
    firstName: "John",
    lastName: "Doe",
    transcriptName: "Computer Science Degree",
    receipientName: "John Doe",
    studentNo: "9283723",
    dateOfBirth: "1995-05-15",
    description: "Bachelor's Degree in Computer Science",
    degreeName: "Bachelor of Science",
    semesters: [
      {
        year: "2020",
        term: "Fall",
        module: "Computer Vision",
        grade: "A",
        credits: "4",
      },
      {
        year: "2020",
        term: "Spring",
        module: "Natural Language Processing",
        grade: "B+",
        credits: "3",
      },
      {
        year: "2021",
        term: "Fall",
        module: "Machine Learning",
        grade: "A-",
        credits: "4",
      },
    ],
  },
  {
    firstName: "Susan",
    lastName: "Low",
    transcriptName: "Computer Science Degree",
    receipientName: "Susan Low",
    studentNo: "8237281",
    dateOfBirth: "1995-05-15",
    description: "Bachelor's Degree in Computer Science",
    degreeName: "Bachelor of Science",
    semesters: [
      {
        year: "2020",
        term: "Fall",
        module: "Computer Vision",
        grade: "A",
        credits: "4",
      },
      {
        year: "2020",
        term: "Spring",
        module: "Natural Language Processing",
        grade: "B+",
        credits: "3",
      },
      {
        year: "2021",
        term: "Fall",
        module: "Machine Learning",
        grade: "A-",
        credits: "4",
      },
    ],
  },

  {
    firstName: "Jeremy",
    lastName: "Tan",
    transcriptName: "Computer Science Degree",
    receipientName: "Jeremy Tan",
    studentNo: "2372338",
    dateOfBirth: "1995-05-15",
    description: "Bachelor's Degree in Computer Science",
    degreeName: "Bachelor of Science",
    semesters: [
      {
        year: "2020",
        term: "Fall",
        module: "Computer Vision",
        grade: "A",
        credits: "4",
      },
      {
        year: "2020",
        term: "Spring",
        module: "Natural Language Processing",
        grade: "B+",
        credits: "3",
      },
      {
        year: "2021",
        term: "Fall",
        module: "Machine Learning",
        grade: "A-",
        credits: "4",
      },
    ],
  },

  {
    firstName: "Clara",
    lastName: "Chen",
    transcriptName: "Computer Science Degree",
    receipientName: "Clara Chen",
    studentNo: "7273291",
    dateOfBirth: "1995-05-15",
    description: "Bachelor's Degree in Computer Science",
    degreeName: "Bachelor of Science",
    semesters: [
      {
        year: "2020",
        term: "Fall",
        module: "Computer Vision",
        grade: "A",
        credits: "4",
      },
      {
        year: "2020",
        term: "Spring",
        module: "Natural Language Processing",
        grade: "B+",
        credits: "3",
      },
      {
        year: "2021",
        term: "Fall",
        module: "Machine Learning",
        grade: "A-",
        credits: "4",
      },
    ],
  },
];
